server:
  port: 8103
spring:
  profiles:
    active: yzq
mybatis:
  mapper-locations: classpath*:com.cskaoyan.order.dal/persistence/*Mapper.xml"
  type-aliases-package: com.cskaoyan.order.dal.entitys

#  新增rocketMQ配置
mq:
  nameserver:
    addr: 127.0.0.1:9876
  topicname: order


