server:
  port: 8102
spring:
  profiles:
    active: devcaojun
mybatis:
  mapper-locations: classpath*:com.cskaoyan.shopping.dal/persistence/*Mapper.xml"
  type-aliases-package: com.cskaoyan.shopping.dal.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
